# Generated by Django 5.2.1 on 2025-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('studentId', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
