# Generated by Django 5.2.1 on 2025-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_rename_employee_studet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studet',
            new_name='Student',
        ),
    ]
